env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - 'plugin:prettier/recommended' 
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - prettier
rules: 
  eqeqeq: 'error'                # Enforce the use of === and !==
  curly: 'error'                 # Require following curly brace conventions
  no-unused-vars: 'warn'         # Warn about unused variables
  no-console: 'off'              # Turning off console warnings, change to 'warn' or 'error' as needed
  prettier/prettier: 'error'     # Turns Prettier rules into linting errors
  '@typescript-eslint/no-unused-vars': 'warn' # TypeScript-specific unused vars rule
